# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/ShivamX087/kernel_motorola_vicky
          kernel-dir: kernel
          kernel-branch: android12-5.10
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          android-version: 12
          aosp-clang-version: r530567
          disable-lto: true
          anykernel3: true
